### ISSUE TITLE
Migrations-Command not working as expected. Don't load the OpenCFP production.yaml

### ISSUE THREAD

**Issue by andygrunwald** [opencfp/opencfp#1125]
# Steps required to reproduce the problem

1. Setup the webserver as described in the README.md
2. Setup a new database and a user
3. Configure your production.yml like
```
application:
  ...

database:
  host: localhost
  database: cfp
  dsn: mysql:dbname=cfp;host=localhost
  user: opencfp
  password: mypass

log:
  level: error

mail:
  ...

talk:
  categories:
    ...
  levels:
    ...
  types:
    ...
```

# Expected Result

* Database setup / migration runs

# Actual Result

```
root@agrunwald-uiconf-opencfp:/var/www/opencfp# CFP_ENV=production vendor/bin/phinx migrate
Phinx by CakePHP - https://phinx.org. 0.9.2

using config file ./phinx.php
using config parser php
using migration paths
 - /var/www/opencfp-1.5.3/migrations
warning no environment specified, defaulting to: production
using adapter mysql
using database cfp

In MysqlAdapter.php line 115:

  There was a problem connecting to the database: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'


migrate [-c|--configuration CONFIGURATION] [-p|--parser PARSER] [-e|--environment ENVIRONMENT] [-t|--target TARGET] [-d|--date DATE] [-x|--dry-run]
``` 

It seems that the config is not read at all. Because it is using `root` instead of the `cfp` user (which is configured).

Any idea?
