### ISSUE TITLE
Visiting the home page returns links to "localhost" urls and shows "Internal Server Error!"

### ISSUE THREAD

**Issue by JonTheNiceGuy** [opencfp/opencfp#1132]
# Steps required to reproduce the problem

1. On a server running Debian 9.4, with php 7.2 installed from packages.sury.org and nginx, with the php-fastcgi configured and working (https://jon.sprig.gs/blog is hosted on the same setup).
1. Ensure /etc/php/7.2/cgi/php.ini has the following line: `error_log = syslog`
1. Define a server (cfp.oggcamp.org) in /etc/nginx/site-enabled following nginx config statement. Restart nginx.
1. Run certbot to obtain a TLS certificate from LetsEncrypt.
1. Create /var/www/cfp.oggcamp.org/config/production.yml with the following values:

```
application:
  title: OpenCFP
  url: https://cfp.oggcamp.org
  email: oggcamp@mailman.lug.org.uk
  eventurl: https://oggcamp.org
  event_location: Sheffield, UK
  enddate: Jun. 16, 2018
  show_submission_count: false
  airport: MCR
  arrival: 2018-08-18
  departure: 2018-08-19
  secure_ssl: true
  online_conference: false
  date_format: YYYY-MM-DD
  date_timezone: "Europe/London"
  coc_link: https://oggcamp.org/code-of-conduct/
  show_contrib_banner: true
  venue_image_path: /assets/img/venue.jpg

database:
  host: 127.0.0.1
  database: REDACTED
  dsn: mysql:dbname=REDACTED;host=127.0.0.1
  user: REDACTED
  password: REDACTED

log:
  level: error

mail:
  host: 127.0.0.1
  port: 25
  username: ~
  password: ~
  encryption: ~
  auth_mode: ~

talk:
  categories:
    software: Free and Open Source Software
    hardware: Open Hardware
    rights: Digital Rights
    culture: Free Culture
    personal: Personal Skills
    other: Other
  levels:
    entry: Entry level
    mid: Mid-level
    advanced: Advanced
  types:
    regular: Single session (25 mins)
    double: Double sesson (55 mins)
security:
  firewalls:
    secured_area:
      form_forgot:
        csrf_parameter: _csrf_security_token
        csrf_token_id: forgot_password

reviewer:
  users:
    -
```
1. Execute: `tail -f -n 0 $(find /var/log -type f)`
1. Visit https://cfp.oggcamp.org

# Expected Result

* Working site OR log entries identifying why there is an internal server error.

# Actual Result

* Links don't work, "Internal Server Error!" message and nothing in the logs.

Happy to provide anything I can to get this working! :)
