### ISSUE TITLE
ResetEmailer echoes stracktrace in case there's a problem sending message

### ISSUE THREAD

**Issue by samdark** [opencfp/opencfp#1241]
https://github.com/opencfp/opencfp/blob/master/src/Domain/Services/ResetEmailer.php#L71

That's not a good way to handle errors. Stacktrace is very verbose in this case and contains sensitive information. Especially in case of resetting password.

To reproduce set wrong password in `production.yml` and try resetting password:

```yaml
mail:
  host: bla.bla.com
  port: 587
  username: noreply@bla.bla.com
  password: wrong_password
  encryption: tls
  auth_mode: ~
```
