### ISSUE TITLE
Installation problem : lots of 404s

### ISSUE THREAD

**Issue by senf666** [opencfp/opencfp#169]
Hi,
I'm getting a lot of 404s for various pages eg:

```
File does not exist: /var/www/html/cfp.chickenkiller.com/web/dashboard, referer: http://cfp.chickenkiller.com/
File does not exist: /var/www/html/cfp.chickenkiller.com/web/signup, referer: http://cfp.chickenkiller.com/
```

It's a brand new install at http://cfp.chickenkiller.com/ 

**php and apache versions**

```
php -v
PHP 5.6.2 (cli) (built: Oct 17 2014 07:22:10)


httpd -v
Server version: Apache/2.2.15 (Unix

apachectl -t -D DUMP_MODULES
Loaded Modules:

 rewrite_module (shared)
 php5_module (shared)
Syntax OK
```

**phinx**

```
$ vendor/bin/phinx migrate --environment=development
Phinx by Rob Morgan - http://phinx.org. version 0.3.8

using config file ./phinx.yml
using config parser yaml
using migration path /var/www/html/cfp.chickenkiller.com/migrations
using environment development
using adapter mysql
using database cfp
 == 0 Schema: migrating
 == 0 Schema: migrated 0.2620s
 == 20140823091041 Favorites: migrating
 == 20140823091041 Favorites: migrated 0.0497s
 == 20140828144530 AddIdToSpeakerTable: migrating
 == 20140828144530 AddIdToSpeakerTable: migrated 0.1414s
 == 20140828145029 AddHotelAndTransportationCostFields: migrating
 == 20140828145029 AddHotelAndTransportationCostFields: migrated 0.1415s
 == 20140902174929 RemoveSpeakerTable: migrating
 == 20140902174929 RemoveSpeakerTable: migrated 0.2165s
All Done. Took 0.8839s
```

**http.conf**

```
<VirtualHost *:80>
    ServerAdmin asdasd@asd.com
    DocumentRoot /var/www/html/cfp.chickenkiller.com/web
    ServerName cfp.chickenkiller.com
    ErrorLog logs/cfp.chickenkiller-error_log
    CustomLog logs/cfp.chickenkiller-access_log common
</VirtualHost>
```

**development.yml**

```
application:
  title: OpenCFP
  url: http://cfp.chickenkiller.com
  email: contact@openconf.com
  eventurl: http://myenvent.com
  enddate: Oct. 14th, 2016
  airport: MIA
  arrival: 2014-10-26
  departure: 2014-10-31
  secure_ssl: false

cache:
  enabled: false

database:
...........
```

Any ideas ?
