### ISSUE TITLE
Error connecting to database

### ISSUE THREAD

**Issue by mattstratton** [opencfp/opencfp#372]
# Steps required to reproduce the problem

1. Installed opencfp according to instructions
2. Configured AWS RDS MySQL instance
3. Attempt to load website

# Expected Result

* Website loads :)

# Actual Result

* Receive error 500 with the following in the Apache error log:

```[Wed Mar 09 22:09:52.775618 2016] [:error] [pid 4851] [client 107.210.248.58:37834] PHP Fatal error:  Uncaught exception 'Exception' with message 'There was a problem connecting to the database. Make sure to use proper DSN format. See: http://php.net/manual/en/pdo.connections.php' in /var/www/opencfp/classes/Provider/DatabaseServiceProvider.php:57\nStack trace:\n#0 /var/www/opencfp/classes/Provider/DatabaseServiceProvider.php(16): OpenCFP\\Provider\\DatabaseServiceProvider->raiseDatabaseConnectionIssue()\n#1 /var/www/opencfp/vendor/silex/silex/src/Silex/Application.php(178): OpenCFP\\Provider\\DatabaseServiceProvider->register(Object(OpenCFP\\Application))\n#2 /var/www/opencfp/classes/Application.php(63): Silex\\Application->register(Object(OpenCFP\\Provider\\DatabaseServiceProvider))\n#3 /var/www/opencfp/web/index.php(11): OpenCFP\\Application->__construct('/var/www/opencf...', Object(OpenCFP\\Environment))\n#4 {main}\n  thrown in /var/www/opencfp/classes/Provider/DatabaseServiceProvider.php on line 57```

I confirmed that the web server can connect to the RDS instance via the MySQL command line, and the migration works fine.

This is what my database configuration section of `production.yml` looks like (password and hostname redacted)

```
database:
  host: xxxxxxxx.us-east-1.rds.amazonaws.com
  database: dod_cfp
  dsn: mysql:dbname=dod_cfp;host=xxxxxx.us-east-1.rds.amazonaws.com
  user: dodchidb
  password: xxxxx
```
